import { createClient, SupabaseClient } from '@supabase/supabase-js'

let supabaseInstance: SupabaseClient | null = null

export function getSupabase(): SupabaseClient {
  if (supabaseInstance) return supabaseInstance

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

  if (!supabaseUrl || !supabaseAnonKey) {
    // Return a mock client that will error on use - prevents build failures
    throw new Error('Supabase not configured')
  }

  supabaseInstance = createClient(supabaseUrl, supabaseAnonKey)
  return supabaseInstance
}

// For convenience in components - will throw if not configured
export const supabase = typeof window !== 'undefined'
  ? getSupabase()
  : (null as unknown as SupabaseClient)

// Types based on our schema
export type IdeaStatus =
  | 'draft'
  | 'generating_prd'
  | 'pending_approval'
  | 'approved'
  | 'rejected'
  | 'building'
  | 'shipped'
  | 'archived'

export type InputType = 'manual' | 'tweet' | 'bug' | 'feature' | 'voice'

export type ProjectDNA = 'chrome-extension' | 'adhd-game' | 'utility-app' | 'api' | 'script' | 'world-builder'

export type BuildStatus = 'queued' | 'running' | 'paused' | 'completed' | 'failed'

export interface Idea {
  id: string
  title: string
  raw_input: string
  input_type: InputType
  source_url: string | null
  source_metadata: Record<string, unknown>
  prd: string | null
  prd_approved: boolean
  project_dna: ProjectDNA
  score: number
  tags: string[]
  status: IdeaStatus
  created_at: string
  updated_at: string
}

// Build report structure (generated by verification system)
export interface BuildReport {
  success: boolean
  projectType: string
  title: string
  expected: {
    description: string
    items: string[]
  }
  actual: {
    description: string
    items: { name: string; status: 'pass' | 'fail'; detail: string }[]
  }
  summary: {
    headline: string
    explanation: string
    location: string
    nextSteps: string[]
  }
  technical: {
    buildId: string
    repoUrl: string | null
    deployedUrl: string | null
    errorMessage: string | null
  }
}

export interface Build {
  id: string
  idea_id: string
  status: BuildStatus
  progress: number
  current_phase: string | null
  phases: unknown[]
  logs: string[]
  error_message: string | null
  repo_url: string | null
  deployed_url: string | null
  pr_url: string | null
  cost_estimate: number
  actual_cost: number
  started_at: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
  title?: string
  project_dna?: ProjectDNA
  build_report?: BuildReport | null
}

export interface QueueStats {
  status: IdeaStatus
  count: number
  latest: string
}
