-- Add scaffold output columns to dj_builds
-- These store the generated CLAUDE.md and task list from the scaffold agent

-- The actual build instructions generated by the scaffold agent
alter table dj_builds add column if not exists claude_md text default null;

-- Structured task list from scaffold (JSON array of {phase, task, detail, priority, done})
alter table dj_builds add column if not exists scaffold_tasks jsonb default null;

-- Build report (structured verification results)
alter table dj_builds add column if not exists build_report jsonb default null;

-- Add 'scaffolded' as a valid build status
alter table dj_builds drop constraint if exists dj_builds_status_check;
alter table dj_builds add constraint dj_builds_status_check check (
  status in ('queued', 'scaffolded', 'running', 'paused', 'completed', 'failed')
);
